apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: first-persistentVolumeClaim
spec: # the specifications need to match the specifications of the persistent volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard