apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3 # number of replicas
  template: # template: pod infos
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: nginx-pod

