apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: first-storageClass
provisioner: kubernetes.io/gce-pc # provision a disk on the Google Cloud Engine Platform
parameters:
  type: pd-standard # create a standard disk (default)
  fstype: ext4
  replication: none
