apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: first-storageClass-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    storageClassName: first-storageClass
