apiVersion: v1
kind: Service
metadata:
  name: svc-news-portal
spec:
  type: NodePort
  selector:
    app: news-portal
  ports:
    - port: 80 #targetPort: 80 #target port will be the same as the container port
      nodePort: 30000 #port exposed on the node
  