apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: news-portal-replicaset
spec:
  template: # template: pod infos
    metadata:
      name: news-portal
      labels:
        app: news-portal
    spec:
      containers:
      - name: news-portal
        image: aluracursos/portal-noticias:1
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: portal-configmap
  replicas: 3 # number of replicas
  selector:
    matchLabels:
      app: news-portal



